# Generated by Django 5.2.17 on 2026-08-16 15:28

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import kai.models
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('api_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', kai.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LookupValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('value', models.TextField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lookup_values',
                'indexes': [django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('value'), name='gin_trgm_ops'), name='idx_lookup_values_value_trgm')],
                'constraints': [models.UniqueConstraint(fields=('category', 'value'), name='uniq_lookup_category_value')],
            },
        ),
        migrations.CreateModel(
            name='Pcap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('file', models.FileField(blank=True, max_length=500, upload_to='pcaps/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('event', models.TextField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('platform', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('sponsor', models.TextField(blank=True, null=True)),
                ('baseline', models.BooleanField(default=False, null=True)),
                ('hmi', models.TextField(blank=True, null=True)),
                ('plc', models.TextField(blank=True, null=True)),
                ('ot_protocols', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None)),
                ('source_host', models.TextField(blank=True, null=True)),
                ('network_interface', models.TextField(blank=True, null=True)),
                ('capture_tool', models.TextField(blank=True, null=True)),
                ('ticket_reference', models.TextField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.TextField(blank=True, null=True)),
                ('packet_count', models.IntegerField(blank=True, null=True)),
                ('capture_start_time', models.DateTimeField(blank=True, null=True)),
                ('capture_end_time', models.DateTimeField(blank=True, null=True)),
                ('capture_duration_seconds', models.FloatField(blank=True, null=True)),
                ('file_format', models.TextField(blank=True, null=True)),
                ('snaplen', models.IntegerField(blank=True, null=True)),
                ('link_layer_type', models.TextField(blank=True, null=True)),
                ('average_packet_size', models.FloatField(blank=True, null=True)),
                ('data_rate_bytes_per_sec', models.FloatField(blank=True, null=True)),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('filename', 'description', 'notes', 'event', 'source_host', 'ticket_reference', 'hmi', 'plc', 'sector', config='english'), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pcaps',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tags',
                'indexes': [django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('name'), name='gin_trgm_ops'), name='index_tags_on_name_trgm')],
            },
        ),
        migrations.CreateModel(
            name='PcapTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcap_tags', to='kai.pcap')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcap_tags', to='kai.tag')),
            ],
            options={
                'db_table': 'pcap_tags',
            },
        ),
        migrations.AddField(
            model_name='pcap',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pcaps', through='kai.PcapTag', to='kai.tag'),
        ),
        migrations.AddConstraint(
            model_name='pcaptag',
            constraint=models.UniqueConstraint(fields=('pcap', 'tag'), name='uniq_pcap_tags_pcap_tag'),
        ),
        migrations.AddIndex(
            model_name='pcap',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='index_pcaps_on_search_vector'),
        ),
        migrations.AddIndex(
            model_name='pcap',
            index=django.contrib.postgres.indexes.GinIndex(fields=['ot_protocols'], name='index_pcaps_on_ot_protocols'),
        ),
        migrations.AddIndex(
            model_name='pcap',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('filename'), name='gin_trgm_ops'), name='index_pcaps_on_filename'),
        ),
        migrations.AddIndex(
            model_name='pcap',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('event'), name='gin_trgm_ops'), name='index_pcaps_on_event'),
        ),
    ]
