# Generated by Django 5.2.17 on 2026-08-24 04:02

import django.contrib.postgres.search
from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kai', '0004_clear_seeded_lookup_values'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pcap',
            name='index_pcaps_on_search_vector',
        ),
        migrations.RemoveField(
            model_name='pcap',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='pcap',
            name='capture_tool',
        ),
        migrations.RemoveField(
            model_name='pcap',
            name='ticket_reference',
        ),
        migrations.AddField(
            model_name='pcap',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('filename', 'description', 'notes', 'event', 'source_host', 'hmi', 'plc', 'sector', config='english'), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddIndex(
            model_name='pcap',
            index=GinIndex(fields=['search_vector'], name='index_pcaps_on_search_vector'),
        ),
    ]
